keys:
  - &user_age age1vfhs5y5nmtmw9n9tq5eqtx07a5u8j2qfjenjj08dmalaccesmq9quzctvw
  - &backup_age age1xxpektsl2r0hsarjyhavsprxxsssm7ca4udluz5fpk6kxjrud5gq94ead0

creation_rules:
  - path_regex: secrets/.*\.enc$
    key_groups:
      - age:
          - *user_age
          - *backup_age
